import { test, expect } from '@playwright/test';

// Required fields for API-based request creation
const BASE_DATA = {
  govProjectType: 'PoC',
  businessUnit: 'IDG',
  productSoftwareType: 'Hardware',
  productEndUser: ['Lenovo internal employee/contractors'],
  userRegion: ['PRC'],
};

test.describe('Governance Requests', () => {
  const createdRequestIds: string[] = [];

  test.afterAll(async () => {
    if (createdRequestIds.length > 0) {
      await fetch('http://localhost:4001/api/dev/delete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ governanceRequests: createdRequestIds }),
      });
    }
  });

  // Reset all mandatory flags so tests aren't affected by manual DB config
  let mandatoryRulesToRestore: string[] = [];
  test.beforeAll(async ({ request }) => {
    const resp = await request.get('http://localhost:4001/api/dispatch-rules/', {
      headers: { 'X-Dev-Role': 'admin' },
    });
    const body = await resp.json();
    const rules = Array.isArray(body) ? body : (body.data ?? []);
    for (const rule of rules) {
      if (rule.isMandatory) {
        mandatoryRulesToRestore.push(rule.ruleCode);
        await request.put(`http://localhost:4001/api/dispatch-rules/${rule.ruleCode}`, {
          headers: { 'X-Dev-Role': 'admin' },
          data: { isMandatory: false },
        });
      }
    }
  });
  test.afterAll(async ({ request }) => {
    // Restore mandatory flags
    for (const code of mandatoryRulesToRestore) {
      await request.put(`http://localhost:4001/api/dispatch-rules/${code}`, {
        headers: { 'X-Dev-Role': 'admin' },
        data: { isMandatory: true },
      });
    }
  });

  test('list page loads with table', async ({ page }) => {
    await page.goto('/requests');
    await expect(page.getByRole('heading', { name: 'Governance Requests' })).toBeVisible();
    await expect(page.locator('text=New Request')).toBeVisible();
  });

  test('create new request via form', async ({ page }) => {
    await page.goto('/governance/create');
    await expect(page.getByRole('heading', { name: 'Create Governance Request' })).toBeVisible();

    // Request ID placeholder should be visible (auto-generated by backend)
    await expect(page.getByTestId('request-id-placeholder')).toBeVisible();

    // Project type selector should be visible
    await expect(page.getByTestId('select-gov-project-type')).toBeVisible();

    // Select required fields
    await page.getByTestId('select-gov-project-type').selectOption('PoC');
    await page.getByTestId('select-business-unit').selectOption('IDG');
    await page.getByTestId('select-product-software-type').selectOption('Hardware');
    await page.getByTestId('checkbox-end-user-internal').check();
    await page.getByTestId('checkbox-region-prc').check();

    // Click submit and wait for API response + navigation (no title required)
    const [response] = await Promise.all([
      page.waitForResponse((resp) => resp.url().includes('/governance-requests') && resp.request().method() === 'POST', { timeout: 15000 }),
      page.getByTestId('save-draft-btn').click(),
    ]);
    expect(response.status()).toBe(200);
    const created = await response.json();
    createdRequestIds.push(created.requestId);
    expect(created.requestId).toMatch(/^EGQ\d{10}$/);

    await page.waitForURL(/\/governance\/EGQ/, { timeout: 10000 });
    expect(page.url()).toContain('/governance/EGQ');
  });

  test('view request detail page', async ({ page }) => {
    // First create a request via API (title auto-set to EGQ ID)
    const response = await page.request.post('http://localhost:4001/api/governance-requests', {
      data: { ...BASE_DATA },
    });
    const gr = await response.json();
    createdRequestIds.push(gr.requestId);

    await page.goto(`/governance/${gr.requestId}`);
    // Wait for the request ID to appear on the detail page heading
    await expect(page.getByRole('heading', { name: gr.requestId })).toBeVisible({ timeout: 15000 });
  });

  test('status filter dropdown filters results', async ({ page }) => {
    // Ensure a Draft request exists
    const statusFilterResp = await page.request.post('http://localhost:4001/api/governance-requests', {
      data: { ...BASE_DATA, title: 'Status Filter E2E Test' },
    });
    createdRequestIds.push((await statusFilterResp.json()).requestId);
    await page.goto('/requests');
    await expect(page.getByRole('heading', { name: 'Governance Requests' })).toBeVisible();
    // Status filter should be a dropdown select
    const statusSelect = page.getByTestId('status-filter');
    await expect(statusSelect).toBeVisible();
    // Select "Draft" and wait for the filtered API response
    const [response] = await Promise.all([
      page.waitForResponse(
        (resp) => resp.url().includes('/governance-requests') && resp.url().includes('status=Draft') && resp.request().method() === 'GET',
        { timeout: 10000 },
      ),
      statusSelect.selectOption('Draft'),
    ]);
    expect(response.status()).toBe(200);
    const body = await response.json();
    // All returned rows should have Draft status
    for (const row of body.data) {
      expect(row.status).toBe('Draft');
    }
  });

  test('search box filters requests', async ({ page }) => {
    await page.goto('/requests');
    await expect(page.getByRole('heading', { name: 'Governance Requests' })).toBeVisible();
    // Search input should be visible
    const searchInput = page.getByPlaceholder('Search by Request ID or Title...');
    await expect(searchInput).toBeVisible();
    // Type a search term
    await searchInput.fill('GR-');
    // Wait for debounced search to trigger
    await page.waitForTimeout(500);
    // Page should still be functional
    await expect(page.getByRole('heading', { name: 'Governance Requests' })).toBeVisible();
  });

  test('requestor filter input filters results', async ({ page }) => {
    await page.goto('/requests');
    await expect(page.getByRole('heading', { name: 'Governance Requests' })).toBeVisible();
    // Requestor filter input should be visible
    const requestorInput = page.getByTestId('requestor-filter');
    await expect(requestorInput).toBeVisible();
    // Type a requestor name and wait for debounced API call
    const [response] = await Promise.all([
      page.waitForResponse(
        (resp) => resp.url().includes('/governance-requests') && resp.url().includes('requestor=') && resp.request().method() === 'GET',
        { timeout: 10000 },
      ),
      requestorInput.fill('system'),
    ]);
    expect(response.status()).toBe(200);
  });

  test('date preset dropdown and custom date pickers work', async ({ page }) => {
    await page.goto('/requests');
    await expect(page.getByRole('heading', { name: 'Governance Requests' })).toBeVisible();
    // Period dropdown should be visible with default "All Time"
    const dateSelect = page.getByTestId('date-filter');
    await expect(dateSelect).toBeVisible();
    // Date inputs should NOT be visible by default
    await expect(page.locator('input[type="date"]')).toHaveCount(0);
    // Select "Custom" to reveal date pickers
    await dateSelect.selectOption('custom');
    await expect(page.getByTestId('custom-date-from')).toBeVisible();
    await expect(page.getByTestId('custom-date-to')).toBeVisible();
  });

  test('column header sort indicators appear on click', async ({ page }) => {
    await page.goto('/requests');
    await expect(page.getByRole('heading', { name: 'Governance Requests' })).toBeVisible();
    // Click on "Title" column header to sort
    await page.getByRole('columnheader', { name: /Title/ }).click();
    await page.waitForTimeout(500);
    // Sort indicator should appear (▲ for ASC)
    await expect(page.getByTestId('sort-indicator-title')).toBeVisible();
  });

  test('submit draft request via detail page', async ({ page }) => {
    // Create a Draft request via API
    const resp = await page.request.post('http://localhost:4001/api/governance-requests', {
      data: { ...BASE_DATA, title: 'Submit Flow E2E Test' },
    });
    const gr = await resp.json();
    createdRequestIds.push(gr.requestId);
    expect(gr.status).toBe('Draft');

    // Navigate to detail page
    await page.goto(`/governance/${gr.requestId}`);
    await expect(page.getByTestId('submit-request-btn')).toBeVisible();

    // Click Submit and intercept the PUT response
    const [submitResp] = await Promise.all([
      page.waitForResponse(
        (r) => r.url().includes(`/governance-requests/${gr.requestId}/submit`) && r.request().method() === 'PUT',
        { timeout: 10000 },
      ),
      page.getByTestId('submit-request-btn').click(),
    ]);
    expect(submitResp.status()).toBe(200);
    const updated = await submitResp.json();
    expect(updated.status).toBe('Submitted');

    // Submit button should disappear (no longer Draft)
    await expect(page.getByTestId('submit-request-btn')).not.toBeVisible();
  });

  test('export CSV button is visible', async ({ page }) => {
    // Create a request first so data exists
    const csvResp = await page.request.post('http://localhost:4001/api/governance-requests', {
      data: { ...BASE_DATA, title: 'CSV Export Test' },
    });
    createdRequestIds.push((await csvResp.json()).requestId);
    await page.goto('/requests');
    await expect(page.getByRole('heading', { name: 'Governance Requests' })).toBeVisible();
    // Wait for data to load
    await page.waitForTimeout(1000);
    // Export CSV button should be visible
    await expect(page.getByTestId('export-csv-btn')).toBeVisible();
    await expect(page.getByTestId('export-csv-btn')).toHaveText(/Export CSV/);
  });

  test('create form shows rule YES/NO toggles and domain preview', async ({ page }) => {
    await page.goto('/governance/create');
    await expect(page.getByRole('heading', { name: 'Create Governance Request' })).toBeVisible();

    // Wait for compliance rules section to load (inside Governance Scope Determination)
    const rulesSection = page.getByTestId('dispatch-rules-section');
    await expect(rulesSection).toBeVisible({ timeout: 10000 });

    // YES/NO toggles should be visible for seed rules
    await expect(page.getByTestId('rule-toggle-AI-yes')).toBeVisible();
    await expect(page.getByTestId('rule-toggle-AI-no')).toBeVisible();
    await expect(page.getByTestId('rule-toggle-PII-yes')).toBeVisible();

    // Triggered domains section should be visible with empty state
    await expect(page.getByTestId('triggered-domains-section')).toBeVisible();

    // Click YES on AI rule → should show RAI domain chip
    await page.getByTestId('rule-toggle-AI-yes').click();
    await expect(page.getByTestId('domain-chip-RAI')).toBeVisible();

    // Click YES on PII rule → should also show DP domain chip
    await page.getByTestId('rule-toggle-PII-yes').click();
    await expect(page.getByTestId('domain-chip-DP')).toBeVisible();

    // Click NO on AI rule → RAI chip should disappear
    await page.getByTestId('rule-toggle-AI-no').click();
    await expect(page.getByTestId('domain-chip-RAI')).not.toBeVisible();
  });

  test('create form shows business unit dropdown', async ({ page }) => {
    await page.goto('/governance/create');
    await expect(page.getByRole('heading', { name: 'Create Governance Request' })).toBeVisible();

    // BU dropdown should be visible
    const buSelect = page.getByTestId('select-business-unit');
    await expect(buSelect).toBeVisible();

    // Select a value
    await buSelect.selectOption('IDG');
    await expect(buSelect).toHaveValue('IDG');
  });

  test('create request with BU and verify on detail page', async ({ page }) => {
    await page.goto('/governance/create');
    await expect(page.getByRole('heading', { name: 'Create Governance Request' })).toBeVisible();

    // Select required fields
    await page.getByTestId('select-gov-project-type').selectOption('PoC');
    await page.getByTestId('select-business-unit').selectOption('Moto');
    await page.getByTestId('select-product-software-type').selectOption('Hardware');
    await page.getByTestId('checkbox-end-user-internal').check();
    await page.getByTestId('checkbox-region-prc').check();

    // Submit
    const [response] = await Promise.all([
      page.waitForResponse((resp) => resp.url().includes('/governance-requests') && resp.request().method() === 'POST', { timeout: 15000 }),
      page.getByTestId('save-draft-btn').click(),
    ]);
    expect(response.status()).toBe(200);
    const created = await response.json();
    createdRequestIds.push(created.requestId);
    expect(created.businessUnit).toBe('Moto');

    // Navigate to detail page
    await page.waitForURL(/\/governance\/EGQ/, { timeout: 10000 });
    // BU should be displayed in the editable select dropdown
    await expect(page.getByTestId('select-business-unit')).toHaveValue('Moto');
  });

  test('create form shows file upload component', async ({ page }) => {
    await page.goto('/governance/create');
    await expect(page.getByRole('heading', { name: 'Create Governance Request' })).toBeVisible();

    // File upload button should be visible
    await expect(page.getByTestId('btn-add-attachment')).toBeVisible();
  });

  test('file upload adds files to list', async ({ page }) => {
    await page.goto('/governance/create');
    await expect(page.getByRole('heading', { name: 'Create Governance Request' })).toBeVisible();

    // Upload a file via the hidden input
    const fileInput = page.getByTestId('input-file-upload');
    await fileInput.setInputFiles({
      name: 'test-doc.txt',
      mimeType: 'text/plain',
      buffer: Buffer.from('Hello World'),
    });

    // File should appear in the attachment list
    const list = page.getByTestId('attachment-list');
    await expect(list).toBeVisible();
    await expect(list.locator('text=test-doc.txt')).toBeVisible();
  });

  test('create request with attachment and verify on detail page', async ({ page }) => {
    await page.goto('/governance/create');
    await expect(page.getByRole('heading', { name: 'Create Governance Request' })).toBeVisible();

    // Select required fields
    await page.getByTestId('select-gov-project-type').selectOption('PoC');
    await page.getByTestId('select-business-unit').selectOption('IDG');
    await page.getByTestId('select-product-software-type').selectOption('Hardware');
    await page.getByTestId('checkbox-end-user-internal').check();
    await page.getByTestId('checkbox-region-prc').check();

    // Upload a file
    const fileInput = page.getByTestId('input-file-upload');
    await fileInput.setInputFiles({
      name: 'e2e-attachment.txt',
      mimeType: 'text/plain',
      buffer: Buffer.from('E2E test attachment content'),
    });
    await expect(page.getByTestId('attachment-list')).toBeVisible();

    // Submit and wait for create + attachment upload
    const [createResp] = await Promise.all([
      page.waitForResponse((resp) => resp.url().includes('/governance-requests') && resp.request().method() === 'POST' && !resp.url().includes('/attachments'), { timeout: 15000 }),
      page.getByTestId('save-draft-btn').click(),
    ]);
    expect(createResp.status()).toBe(200);
    const attachCreated = await createResp.json();
    createdRequestIds.push(attachCreated.requestId);

    // Wait for navigation to detail page
    await page.waitForURL(/\/governance\/EGQ/, { timeout: 10000 });

    // Attachment card should appear on detail page
    await expect(page.getByTestId('attachments-card')).toBeVisible({ timeout: 10000 });
    await expect(page.getByTestId('attachments-card').locator('text=e2e-attachment.txt')).toBeVisible();
  });

  test('non-MSPO PM autocomplete search', async ({ page }) => {
    await page.goto('/governance/create');
    await expect(page.getByRole('heading', { name: 'Create Governance Request' })).toBeVisible();

    // Switch to Non-MSPO
    await page.getByTestId('btn-non-mspo').click();
    await expect(page.getByTestId('input-project-pm')).toBeVisible();

    // Type in PM field to trigger autocomplete search
    const pmInput = page.getByTestId('input-project-pm');
    await pmInput.fill('a');

    // Wait for the employee search API call
    await page.waitForResponse(
      (resp) => resp.url().includes('/employees/search') && resp.request().method() === 'GET',
      { timeout: 10000 },
    );

    // Dropdown with results should appear (wait a bit for debounce + render)
    await page.waitForTimeout(500);
    // There should be dropdown items visible
    const dropdownItems = page.locator('[data-testid^="pm-option-"]');
    const count = await dropdownItems.count();
    expect(count).toBeGreaterThan(0);

    // Click the first option
    await dropdownItems.first().click();

    // Selected PM should be displayed
    await expect(page.getByTestId('pm-selected')).toBeVisible();
  });

  test('create request with compliance rules and view on detail page', async ({ page }) => {
    await page.goto('/governance/create');
    await expect(page.getByRole('heading', { name: 'Create Governance Request' })).toBeVisible();

    // Select required fields
    await page.getByTestId('select-gov-project-type').selectOption('PoC');
    await page.getByTestId('select-business-unit').selectOption('IDG');
    await page.getByTestId('select-product-software-type').selectOption('Software-Web Based');
    await page.getByTestId('checkbox-end-user-external').check();
    await page.getByTestId('checkbox-region-emea').check();

    // Wait for rules to load then toggle AI and PII to YES
    await expect(page.getByTestId('rule-toggle-AI-yes')).toBeVisible({ timeout: 10000 });
    await page.getByTestId('rule-toggle-AI-yes').click();
    await page.getByTestId('rule-toggle-PII-yes').click();

    // Submit and wait for navigation (no title needed — EGQ ID auto-generated)
    const [response] = await Promise.all([
      page.waitForResponse((resp) => resp.url().includes('/governance-requests') && resp.request().method() === 'POST', { timeout: 15000 }),
      page.getByTestId('save-draft-btn').click(),
    ]);
    expect(response.status()).toBe(200);
    const created = await response.json();
    expect(created.requestId).toMatch(/^EGQ\d{10}$/);
    createdRequestIds.push(created.requestId);
    expect(created.ruleCodes).toContain('AI');
    expect(created.ruleCodes).toContain('PII');

    // Should navigate to detail page
    await page.waitForURL(/\/governance\/EGQ/, { timeout: 10000 });

    // Verify rules are displayed on detail page via the scope determination component
    const rulesSection = page.getByTestId('dispatch-rules-section');
    await expect(rulesSection).toBeVisible({ timeout: 10000 });
    // The AI and PII rule toggles should show as selected (YES highlighted)
    await expect(page.getByTestId('rule-toggle-AI-yes')).toBeVisible();
    await expect(page.getByTestId('rule-toggle-PII-yes')).toBeVisible();
  });
});
